# Site settings
title: Sebastian Duerr
description: Machine Learning Engineer and Chief Product Owner
baseurl: "/duerrse" # the subpath of your site, e.g. /blog
url: www.duerr.se # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sebastian
user_description: I'm a Chief Product Owner always searching for the next challenge. In my free time, I volunteer, and lately I have been immersed in deep learning.
project_description: Below find three project of my machine learning and development portfolio.
user_title: Chief Product Owner
email: duerr.sebastian@gmail.com
twitter_username: seduerr91
github_username: seduerr91

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
