title: Hello, world! I'm Sebastian Duerr
description: > # this means to ignore newlines until "baseurl:"
  This is the blog I will using during my upcoming study leave. If I do not publish once a week, I will have to donate to a charity that I do not like.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "www.duerr.se" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: duerrseb

# Author Settings
author: Sebastian Duerr # add your name
author-img: sebastian.jpg # add your photo
about-author: I am a data scientist focusing on deep learning. Always hungry to keep learning. # add description
social-twitter: duerrseb
social-facebook: seduerr
social-github: seduerr91 # add your Github handle
social-linkedin: sebastianduerr
social-email: duerr.sebastian@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
