# Permalinks
permalink:           pretty

# Setup
title:               Dataplexity.eu
tagline:             An all new perspective on data
url:                 http://dataplexity.eu
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Silvio Heinze
  url:               https://silvioheinze.eu
  email:             s.heinze@dataplexity.eu

# Custom vars
version:             1

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
